AmmarAbouZor/tui-journal

Cargo.lock, Cargo.toml, README.md
- This PR migrates [tui-rs ](https://github.com/fdehau/tui-rs)crate to its revival project [ratatui](https://github.com/tui-rs-revival/ratatui)
- It also updates the version for [crossterm crate](https://github.com/crossterm-rs/crossterm) to 0.26
- It moves the source for [tui-textarea](https://github.com/rhysd/tui-textarea) crate from crates.io to their GitHub repo because the support for ratatui isn't published on crates.io yet
=> Migrate from tui-rs to ratatui

.gitignore, Cargo.lock, Cargo.toml, README.md, src/app/runner.rs, src/cli.rs, src/main.rs, src/settings/json_backend.rs, src/settings/mod.rs, src/settings/sqlite_backend.rs
This Pull Request fixes/closes #10 
It changes the following:
- Fixes panic if any field in the config file is missing
- Remove rewriting the implicitly and add a command line argument to write the current settings to the config file
- Add command to print the current configs to the command line.
- Remove the commands get-json-file-path  and get_sqlite-file-path since these infos are already in the print-config command
- Improvements to the settings since they will loaded one time only
=> settings improvements

README.md
This PR adds GitHub badges to the README.
GitHub badges are used to communicate important information dynamically, comprehensive, and dynamically to visitors.  Countless GitHub repositories have those, so I thought adding them would enhance this project's documentation.  I selected my six favourite ones and configured their links as constants in the document such that you can add further badges more easily.
=> [Documentation] Create README Badges

.github/workflows/main.yml, README.md
This PR makes the following improvements to the CI pipeline:
- It changes the name of the job from rust to CI and adjust the naming in GitHub badges
- Adds [Rust Cache Action](https://github.com/marketplace/actions/rust-cache) to the pipeline
=> CI Improvements

src/app/keymap.rs, src/app/ui/commands/mod.rs, src/app/ui/help_popup.rs
This PR fixes #12 
This PR adds the following improvements to the help popup:
1. Keybindings are grouped by commands to remove redundant commands infos in commands table
1. The popup will be divided into two sections: General keybindings and Editor keybindings
1. Editor keybindings section has a description about how VIM and Emacs keybindings are used in the editor
=> Changed: Help popup improvements

README.md, src/app/keymap.rs, src/app/mod.rs, src/app/runner.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/export_popup/mod.rs, src/app/ui/mod.rs, src/settings/export.rs, src/settings/mod.rs
The PR closes #6 
It adds a new function to export the content of the current journal to a file
- While journals' list is in focus pressing `>` opens an export prompt
- In the export prompt the user can specify the path of the export file
- When the prompt is opened, a suggested path will be given: this suggestion is either a predefined path or the current directory as fall back + journal title
- After the export, an optional confirmation prompt  is shown
This PR adds an export section with the following settings:
- default_path: The base path that will be shown in the export prompt. If not specified then it will falls back to the current directory
- show_confirmation: Sets if to show the confirmation prompt after the export is done. Default is true
=> Added: Export current journal's content

src/cli.rs
This PR closes #20 
It fixes the following issues:
1. Backend file will be always recreated if set through CLI arguments
2. Backend Type won't be set according the the CLI path arguments which led to cases where the users specifies for example a json path but the program run with sqlite backend because the backend type predefined like that
=> Fixed setting backend path from CLI

.github/CODEOWNERS, .github/workflows/release.yml
This PR closes #21 
The release action will:
- Be invoked each time a new tag is created
- Create a new release
- Create binaries for Linux x86_x64 , Linux Arm, MacOS, Windows
=> Added: Release CD action

src/app/ui/export_popup/mod.rs
This PR closes #23 
Now the extension will be simply added to the end of the title name instead of using the method set_extension since it replaces what appears to be an extension in the title name
=> Fixed: Export journal extension

Cargo.lock, Cargo.toml, src/app/runner.rs, src/main.rs
This PR brings the following enhancements to the app render loop:
- Changes the render loop using event-stream from crossterm, since the recommended way to run in tokio runtime 
- Remove unnecessary rendering on tick rate since the app doesn't monitor anything outside the user input
=> Changed: Enhance render loop

.github/workflows/main.yml, CITATION.cff
This PR adds a CITATION.cff as well as the corresponding validation step.
CFF is a technology to make software citable such that it can be added to a paper's or presentation's list of references just like a book or an article.  GitHub will render a "Cite this repository" blob on the repository's main page such that visitors can add TUI-Journal to their lists of references.  This can be seen as free advertisement as the software will thus become known to other people.  The validation usually takes only about 10 seconds, so it is not going to have any major impact on the CI's performance and runtime.
I am going to give a presentation on CHANGELOG management strategies next week; in the section on advanced fragment policies, I would like to mention the planned strategy for TUI-Journal (#16). …
=> Added:  CITATION.cff

Cargo.lock, Cargo.toml, README.md, src/app/external_editor.rs, src/app/keymap.rs, src/app/mod.rs, src/app/runner.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/editor/mod.rs, src/settings/export.rs, src/settings/mod.rs
This PR closes #8
- It adds the function to edit the current journal content with an external terminal editor.
- Keybindings are v and <Ctrl-v>
- The editor can be set in the configurations. Config name is 'external_editor'
- If it's not set in the configs then the environment variables VISUAL, EDITOR will be used
=> Added: Edit current journal content in external editor

README.md, src/app/keymap.rs, src/app/mod.rs, src/app/ui/commands/editor_cmd.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/global_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/commands/multi_select_cmd.rs, src/app/ui/entries_list/mod.rs, src/app/ui/footer.rs, src/app/ui/help_popup/mod.rs, src/app/ui/help_popup/multi_select_bindings.rs, src/app/ui/mod.rs
This PR closes #7 
The following was added:
- A new multi-select mode (with `v` keybinding) for journals with the following functions:
1. Toggle selection for the current journal with `space` `enter` `<Ctrl-m>`
2. Select all journals with `a`
3. Select none with `x`
4. Invert selection with `i`
- A delete function inside the multi-select mode to delete many journals at once `d`
- A new tab in the help popup where the keybindings are explained
- Adjustments on the footer to show the important keybindings when multi-select mode is active
- Fixes for small mistakes regarding discarding the journal after the save prompt
=> Added: Multi-selection for journals

.github/workflows/changelog-assembly.yml, .github/workflows/comment-changes.yml, changelog.d/20230609_155121_Kevin_Matthes_update-cargo-install.ron
This PR updates the `cargo-install` Action to its latest version.
In order to make sure that affected workflows still work, I tested them and adjusted the necessary points.  I will add a review in the following to explain the changes.
=> Changed:  bump baptiste0928/cargo-install to v2.1.0

backend/src/json.rs, backend/src/lib.rs, backend/src/sqlite/mod.rs, backend/tests/json/mod.rs, backend/tests/sqlite/mod.rs, src/app/keymap.rs, src/app/mod.rs, src/app/runner.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/commands/multi_select_cmd.rs, src/app/ui/export_popup/mod.rs, src/app/ui/mod.rs, src/app/ui/ui_functions.rs, src/cli.rs, src/cli/commands.rs, src/cli/mod.rs, src/main.rs
This PR closes #35 
It adds the following:
**Export**
- New command inside the multi select mode to export the selected journals to a transfer file in JSON format. Keybinding is `>`
- Command will open the export prompt where the path for the export file can be specified.
- The export prompt uses the same configurations as for exporting a single journal content
- the JSON file contains the journal + the version of the file, which will be helpful if other changes come in the future
**Import**
- The import happens via  a CLI command because it's easier to set path from the shell
- The program will import the journals from the file and the start as usual
- Import errors will be handled inside the program without panic
=> Added: Export Import functions for multiple journals

.github/workflows/main.yml
This PR impressively reduces the time required for linting GitHub Action workflows without any loss of quality.  I tested this change in the repository of Aeruginous before and there, the time was reduced from about 2 minutes with GitHub's super-linter to *5 seconds* with this wrapper around actionlint's Docker image! :rocket:
The super-linter is undoubtedly very powerful as it ships with numerous linters to check almost every coding language; exceptions are Haskell, MATLAB, GNU Octave, CFF, Lex, Julia, Asymptote, and Nim, for example.  This wide range of covered languages is unfortunately also a drawback as we only access the GHA linting, at the moment, because we already have Clippy and rustfmt on the runner and do not need any further linters except for the CFF linter we call …
=> Changed:  improve GHA linting speed dramatically

Cargo.lock, Cargo.toml, README.md, src/app/external_editor.rs
This PR closes #38 
It adds the the option to use git core editor from git global configurations.
Retrieving the editor now follows these priorities:
App config >> Git config >> VISUAL env variable >> EDITOR env variable >> vi
=> Addd: Option to Use Git Configured Editor as External editor

changelog.d/20230608_173148_Ammar_Abou_Zor_main.ron
This PR closes #47 
I used Aeruginouse locally to create a CHANGELOG fragment with the missing changes since the release of Version 0.1.0
=> [Aeruginous] Create Missing CHANGELOG Fragments

.github/workflows/release.yml
This PR should fix failing build in the release GitHub action.
It updates the GitHub action to install rust toolchain since the current one is deprecated
=> Fixed: Release GitHub action

src/app/ui/commands/entries_list_cmd.rs
It feels more intuitive to keep the focus in the journals list after finish editing journal's content in external editor
=> Changed: Keep journals list in focus after closing the external editor

src/app/ui/entry_popup/mod.rs, src/app/ui/entry_popup/tags.rs
This PR closes #60 
- It adds a new function to manage the tags inside the edit/create journals prompt
- Using the keybindings `<Ctrl><Space>` or `<Ctrl>t` a popup with all tags shows up
- Users can add and remove tags from withing the popup prompt, and the changes will be applied on the tags text field in the journals prompt
- This popup covers the edge cases where the users already added new tags but they want to add some from the existing ones.
=> Added: Select-Tags Popup in Create/Edit Journals Prompt

src/app/ui/footer.rs, src/app/ui/mod.rs
This PR adds the keybindings to show and reset the filter in the app main footer.
It adds some improvements and refactoring to the footer source code
=> Changed: Add Filter Keybindings To Footer

README.md, src/app/filter/criterion.rs, src/app/filter/mod.rs, src/app/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/mod.rs
This PR closes #27
- It adds two filter functions to search for the journal titles and content.
- Filter Prompt have now two text boxes for the title and content beside the tags
- This allow the users to apply relatively complex filter in the cost of adding more keystrokes for the simple cases.
- Applying the filter runs in parallel now to achieve the best performance.
- I fixed a mini bug when the result of the filter query one journals only then it will be not highlighted
- Added text indicator to journals title when a filter is applied
=> Added: Search Functions in Filter

.github/workflows/cleanup_cache.yml
This PR adds a GitHub workflow to clean the cache from each PR automatically after closing it.
Since we use caches in different workflows it's a good practice to delete the unwanted ones as soon as the don't needed anymore
=> Added: Create Cleanup Cache GitHub Action

.github/workflows/release.yml
This adds the option to start the release pipeline manually, since it stills under development
=> Allow Release Action To Start Manually

.github/workflows/release.yml
When I just updated my fork, the release workflow created me a release.  The workflow should only work in the original repository, so I fixed this.
=> Fixed:  Prevent release generation in forks

.github/workflows/changelog-assembly.yml
This PR adds the package name to the CHANGELOG assembly workflow in order satisfy the requirements of Aeruginous v3.0.0 for the update of Cargo.lock files; see https://github.com/kevinmatthes/aeruginous-rs/discussions/430.
=> Added:  Add package name to CHANGELOG assembly workflow

.github/workflows/main.yml
This PR reduces the maintenance effort of the main CI definition.
The main CI calls two Actions which are technically just wrappers around Docker images.  By calling them directly instead of binding the wrappers, we do not only save some time, we are furthermore allowed to just call the very latest image available such that we do not need to care about updates for these images anymore.
If you prefer to install updates for the Docker images by merging PRs, we can discuss the required setup and I will adjust the workflow accordingly, then.
=> Changed:  Call Docker images of linters directly

.github/workflows/release.yml, Makefile
This PR closes #84 
- It adds a MakeFile to:
1. Create the binaries for the release on different Environments
1. Run Useful commands locally to check or install with different features sets
- It add the following fixes to the Release Action:
1. Uses MakeFile to create the release's binaries
2. Install missing tools for Linux musl environment 
3. Add the binaries to the release from the release action directly
=> Fixed: Fix Release action using MakeFile

Cargo.lock, Cargo.toml, README.md, src/app/keymap.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/mod.rs
This PR closes #99 
It adds fuzzy finder for the journals using the keymap `u` (I'm still not sure if there is a better keybinding for it).
The selected journal in the main view will stay in sync with the selected one in the fuzzy finder popup
=> Added: Fuzzy Finder for Journals

.github/workflows/release.yml
This PR Adds the following fixes for the Release GitHub Action
- It installs Open SSL dependencies for LINUX MUSL
- Make Creating the release depend on creating the binaries to include them in the release.
=> Fix: Release GitHub Action

Cargo.lock, Cargo.toml, backend/src/sqlite/mod.rs, src/cli/mod.rs
This PR closes #131 
Previous SQLite connection string didn't work on windows machine, because it always add a backslash to the start of the query.
The current change should make the path works on all operating systems. But I still needs to be tested
=> Fix: Fix SQLite connection string path

Cargo.lock, Cargo.toml, src/app/runner.rs, src/app/ui/editor/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/entry_popup/tags.rs, src/app/ui/export_popup/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/footer.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/help_popup/global_bindings.rs, src/app/ui/help_popup/keybindings_table.rs, src/app/ui/help_popup/mod.rs, src/app/ui/help_popup/multi_select_bindings.rs, src/app/ui/mod.rs, src/app/ui/msg_box/mod.rs, src/app/ui/ui_functions.rs, src/main.rs
This PR migrate from the deprecated [tui-rs](https://crates.io/crates/tui) to its reviving project [Ratatui](https://github.com/ratatui-org/ratatui)
This migration enables Updating Crossterm from 0.25 to 0.27 too
I was able to make this migration after updating [tui-textarea](https://crates.io/crates/tui-textarea) on [crates.io](https://crates.io/)
=> Migrate to Ratatui & Update Crossterm to 27

backend/src/sqlite/sqlite_helper.rs, src/app/ui/help_popup/mod.rs, src/cli/mod.rs
This PR closes #184 
- It adds scrollbar for the keybindings table in help popup.
- The scrollbar will be visible only if needed (aka when the view doesn't show all keybindings)
- Clippy Fixes has been added here too
=> Added: Scrollbar for keybindings Overview Popup

src/app/ui/entries_list/mod.rs
This PR closes #183 
It adds a scrollbar to the journals' list when needed with the best possible viewport calculations since the items' height isn't the same
=> Added: Scrollbar to Journals list

src/app/ui/entry_popup/mod.rs
This PR fixes two errors in the footer of the journal popup.
1. Add Optimizations for size calculation for the popup size to fit the footer on almost each terminal size, since it was limited to two lines only.
2. Correcting the keybindings in the footer text
=> Fixed: Journal Popup: Fix Footer Text & Position

README.md, src/app/external_editor.rs, src/app/ui/commands/entries_list_cmd.rs, src/main.rs, src/settings/external_editor.rs, src/settings/mod.rs
This PR closes #206 
It adds a new option in the configuration to save the journal content after closing the external editor automatically.
This adds changes to the configurations structure:
- External-editor changed from a single-line option to a node with two options to configure (command, auto_save)
- Old configurations will still work. In that case the given string will be interpreted as the command and the other fields will have the default values
Here is an example for the new structure
```toml
[external_editor]
command = "nvim"
auto_save = true
``` 
README has been updated and typos has been fixed
=> Added: Autosave Option for  External Editor

src/settings/mod.rs
This PR closes #207
Write Configurations CLI argument checks if any folder in the config path is missing and creates the missing ones
=> Fixed: Write Configurations created needed Directories

src/app/ui/editor/mod.rs
This PR adds a scrollbar to the editor since it's not possible to add text wrapping to it currently
The scrollbar will be rendered when needed only
=> Added: Horizontal Scrollbar to Editor

Cargo.lock, Cargo.toml, src/app/ui/editor/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/entry_popup/tags.rs, src/app/ui/export_popup/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/footer.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/help_popup/mod.rs, src/app/ui/mod.rs, src/app/ui/msg_box/mod.rs, src/app/ui/ui_functions.rs
This PR Upgrades the crates `ratatui` and `tui-textarea`
- `ratatui` has been updated to 0.24 which introduced the following breaking changes:
1. Backend isn't a generic argument anymore
2. Scrollbar state changed its arguments from u16 to usize
- `tui-textarea` uses ratatui as the default feature and it doesn't depend on a specific version from it anymore.
=> Changed: Upgrade Crates Ratatui & Tui-Textarea with breaking changes

README.md, src/app/keymap.rs, src/app/ui/commands/editor_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/editor/mod.rs, src/app/ui/footer.rs, src/app/ui/help_popup/mod.rs, src/app/ui/mod.rs
This PR closes #238 
It adds visual mode for the editor Like in VIM with the ability to select, delete, yank text
Help popup inside the app and README in the repo have been updated with new functionality
=> Added: Visual Mode to Built-in Editor

src/app/ui/entry_popup/mod.rs
This PR closes #245 
- Navigation between input controls in journal popup is possible with the arrow keys now
- Filter Navigation can't be done with the arrows since the arrows are already used to navigate the tags
- Help popup already supports navigation via arrow keys
=> Added: Navigation between journals popup inputs via arrow keys

src/app/ui/mod.rs
This PR closes #248 
- Letter V was always consumed as the visual mode command in editor even when the editor is in insert mode, which prevented typing the letter v
=> Fixed: Letter V can't be typed in built-in editor insert mode

Cargo.lock, Cargo.toml, README.md, src/app/keymap.rs, src/app/ui/commands/editor_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/editor/mod.rs
This PR closes #242 
It adds support to transfer text between the built-in Editor and the operating system clipboard.
I've tested it on Linux (Wayland)
Commands:
- **Copy** with the shortcut `Ctrl-V`
- **Cut** with the shortcut `Ctrl-X`
- **Paste** with the shortcut `Ctrl-P`
=> Added: Support to Copy, Cut and Paste text between Built-in Editor and OS Clipboard

Cargo.lock, Cargo.toml, src/app/ui/help_popup/mod.rs
This PR closes #260 
In this PR:
=> Update Ratatui to 0.25 + Update dependencies

src/app/runner.rs
This PR closes #266 
Since the version 0.26 of crossterm, two events for each key stroke is emitted on Windows (one for press and the other for release) [link](https://github.com/crossterm-rs/crossterm/issues/797), which will be eventually the default behavior on Linux as well. This breaking change led to double key registration on windows. 
With the PR:
- only the keys with the event kind "Press" will be caught and the rest will be ignored.
- The UI won't be re-rendered when the result `not-found` from a key press handling is returned.
=> Ignore key events of types other than press

backend/tests/json/temp_file.rs, src/app/keymap.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/footer.rs, src/app/ui/mod.rs
closes #271 
press ctrl+f to toggle full screen for the selected view:
> The command to switch between the active controls should exit full-screen mode if it active before
I personally liked the other way around (keep it full screen) but let me know if you want this behavior changed!
=> Added: Add full screen mode

src/app/ui/footer.rs, src/app/ui/mod.rs
This PR closes #283 
The height of the main footer will be calculated each time the frame is rendered instead of having it fixed to 1 row height.
This Fix the issue when the text is cut if the footer text is too long for the given terminal space
=> Changed: Main Footer Height is calculated dynamically

src/app/runner.rs
This PR closes #282 
The bug has been introduced a few days ago when the not handled inputs went ignored and didn't caused the UI to be redrawn anymore. This change didn't consider the environment changes like changing the terminal or the font size or resizing the terminal window.
@orhun  This PR return the redraw call back when the input isn't handled in the app logic
=> Fixed: App will be redrawn on not handled input too

.github/workflows/changelog-assembly.yml
This PR fixes #286.
There was a missing `v` prefix.  Now, the tag should be retrievable.
=> Fixed:  CHANGELOG creation logic; fixes #286

README.md, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/app/ui/entry_popup/mod.rs, src/settings/mod.rs
This PR closes #291 
It add the setting field `default_journal_priority` to specify the suggested the journal priority while creating a new journal entry
=> Added: Add Default suggested priority while creating a journal

README.md, backend/src/json.rs, backend/src/lib.rs, backend/src/sqlite/mod.rs, backend/tests/json/mod.rs, backend/tests/sqlite/mod.rs, src/app/mod.rs, src/app/runner.rs, src/app/test/mock.rs, src/cli/commands.rs
This PR closes #295 
It adds the CLI command `assign-priority` which takes the wanted priority is argument and assign it to all journals which doesn't have a priority assigned to them. 
This is helpful for existing journals if the user wants to assign a priority to all the existing journals
=> Added: CLI Sub-Command to assign priority to journals

src/app/runner.rs
This PR closes #300 
It ignores the input events for key release and key repeat events since they aren't handled in the app, which make rendering the UI on them unnecessary.
=> Changed: Skip Rendering the UI on Key-Release & Key-Repeat Events 

README.md, src/app/keymap.rs, src/app/mod.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs, src/settings/mod.rs
This PR closes #301 
It adds the following commands:
- Go to top entry `Home`
- Go to bottom entry `End`
- Page Up/Down through journals using `PageUp` and `PageDown` with default step of 5
Step for Page Up/Down is configurable in the app settings
=> Added: Go to Top/Bottom & Page Up/Down Commands

.github/workflows/changelog-assembly.yml
#288 has shown that the design of the stop condition specification for comment-changes was counter-intuitive.  If not even I as the maintainer can tell the options of my own application apart, my design decisions were obviously wrong.  Thus, I implemented a combination option for comment-changes, ``-@``, which does not care for the actual type of the stop condition -- all valid commit numbers, tags, and branch names are allowed.  Furthermore, the number of possible stop conditions is not restricted to two, anymore -- you are now allowed to define an arbitrary number whereas the first met condition will stop the commit message harvesting.
Due to this new option, ``-S`` and ``-T`` are now superseded because ``-@`` combines their functionality.  Thus, they have been marked deprecated and …
=> Fixed:  Aeruginous:  migrate from deprecated comment-changes option ``-T``

Cargo.toml
Related to #309 
This PR adds rust minimum supported version to `cargo.toml`, since upgrading to the version 1.75 for the early adaptation for native support to async traits caused some confusion
=> Added: Rust minimum supported version to cargo manifest

src/app/ui/commands/editor_cmd.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/global_cmd.rs, src/app/ui/commands/multi_select_cmd.rs, src/app/ui/editor/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/entry_popup/tags.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/mod.rs, src/app/ui/sort_popup/mod.rs
Let the compiler decide where to inline the functions in where the performance not critical, which saved 1 MB from the binary size.
=> Enhancement: Remove explicit inline annotations

src/app/keymap.rs
This PR closes #319 
It seems that the shortcut char '?' isn't recognized on Windows and the simplest solution is to change it to the char 'h' on Windows only since it did never work there.
=> Fixed: Change Help popup shortcut on windows

Cargo.lock, README.md
This PR closes #375.
It adds the flag `--locked` to the install commands in the README file to always use the same version of dependencies as specified in `cargo.lock` file, since a lot of dependencies hasn't reach the version 1 yet and could introduce breaking changes anytime.
This PR update the dependencies too to provide a new release with the updated dependencies since the last release is kind of out-dated...
=> Added `--locked` to Install Instruction & Update dependencies

Makefile, src/app/ui/footer.rs
This PR closes #363 
It adds a new build job to the makefile to specify the arm target for builds with MacOS, then it uses this build job for creating the binaries for release on mac
=> Fixed: Specify arm target on mac build and release

Makefile
GitHub defaults to MacOS architecture now and there is no need to specify it anymore
=> Fix release on MacOS

src/app/ui/editor/mod.rs
This PR closes #386 
It removes the check that the editor must be in visual mode when copying to OS clipboard. 
This Check was there because of the false assumption that we can't select text outside of the visual mode but since we can select text via Shift+Arrow in all editor modes then copying to OS should be supported in all editor modes as well
=> Remove Editor-Mode check when copying to OS

README.md, src/app/ui/commands/editor_cmd.rs, src/app/ui/editor/mod.rs, src/settings/mod.rs
This PR closes #387 
It add the option `sync_os_clipboard` in configuration to enable syncing the clipboard between the built-in editor and the operating system. 
This works with vim keybindings in visual mode and with emacs keybindings in edit mode
=> Added: Optionally Sync Clipboard between Built-in Editor and the Operating System

src/app/ui/help_popup/mod.rs
* Corrects the number of modes to three (Normal-Mode, Edit-Mode and Visual-Mode).
* Corrects some unneeded uppercase characters for editor and Vim words.
=> fix(help): Corrects number of modes and uppercase for editor and Vim

Cargo.lock, Cargo.toml, src/app/ui/editor/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/help_popup/mod.rs
This PR includes:
- Update all dependencies with `cargo update`
- Fix breaking changes for `ratatui` crate after updating to version 0.27.0
=> Fix: Update Dependencies & Fix breaking changes

src/app/ui/help_popup/mod.rs
This PR closes #420 
It provides the request basic emacs bindings to the editor help popup.
I've added the basic ones to move around and delete characters and keys. 
Users can still search online for other powerful emacs keybindings to use within the editor
=> Added: Basic Emacs keybindings to Editor Help Popup

Cargo.lock, Cargo.toml, src/app/runner.rs, src/app/ui/editor/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/export_popup/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/mod.rs, src/app/ui/ui_functions.rs
This PR update the dependencies of the app to the latest versions and deals with the breaking changes introduced in `crossterm` version 0.28 and `Ratatui` version 0.28 and `tui-textarea` with version 0.6
Dealing with the breaking changes was as simple as renaming method or removing them since they are not needed anymore for the most parts, but there was the part when we call to redraw the terminal after closing the external editor. I that position we can't call `resize()` anymore because we don't have access to the terminal dimensions in that position anymore. This issue was resolved be calling `clear()` on the terminal to enforce redrawing everything.
=> Update Dependencies & Fix Crossterm and Raratui Breaking Changes

src/main.rs
This avoids to capture the mouse enabling copy/paste with it.
Closes #422
=> Removes MouseCapture

README.md, src/app/colored_tags.rs, src/app/mod.rs, src/app/ui/entries_list/mod.rs, src/settings/mod.rs
This PR adds the option to make the tags of the journals with different colors.
Currently the colors are hard coded in the file `tui-journal/src/app/colored_tags.rs` and it's still not possible to assign colors to a specific tag.
This option can be disabled from the configuration be setting `colored_tags = false`, and it will be enabled by default.
This is the first step in the implementation for #407. 
After this PR we still need a way for the users to customize the colors and assign them to specific tags + We need to save this configuration in each project with option to export/import them.
@orhun I've tried to choose colors that should be easy to read on most of the famous colorschemes. But please feel free to open a PR with changes to the colors if you find any of them hard to read. …
=> Added: Colored Tags

README.md, src/app/ui/entries_list/mod.rs, src/settings/mod.rs
This PR closes #423 
It provides the configuration to control the visibility of the datum field in journals list with the options `show`, `hide` and `empty_line`.
The description has been added to the configuration section in README as well.
Here is the copy of the added configuration section:
```toml
datum_visibility = "show"  
```
=> Added: Provide Configuration for entries datum visibility

Cargo.lock, README.md, src/app/filter/criterion.rs, src/app/keymap.rs, src/app/mod.rs, src/app/test/filter.rs, src/app/test/mod.rs, src/app/ui/commands/entries_list_cmd.rs, src/app/ui/commands/mod.rs
This PR close #407.
This PR continues the great work of #458 
The whole feature will allow users to cycle through tags from the main view with the keybinding <Ctrl-t>
This was implemented in the PR #458 at first then  I continue working to it to cover some edge cases when there is already a filter applied and added unit tests.
The cycle will now respect the current filter and only change that tags their with the following logic:
* If there is no tags then the first one will be added
* If there is one tag only then the next tag will be applied
* If there is multiple tags then they'll be remove and the first one will be applied
Also the case if the current entry has unsaved changes is considered
Dependencies have been updated here as well
=> Added: Support Cycling Through Tags via Keybinding

Cargo.lock, Cargo.toml, src/app/ui/help_popup/mod.rs
This PR updates the dependencies
It updates `ratatui` and `tui-textarea` to their latest releases to keep them in sync and it provides a small fix for deprecated function in `ratatui` api
=> Fix: Update dependencies & Fix Ratatui breaking changes

.github/workflows/homebrew.yml, README.md
This PR closes #457 
It fixes the old pipeline to ensure the homebrew tab is updated on each release or manually if needed.
This PR updates the README adding nix and homebrew installation instructions.
This install command is
```bash
brew tap AmmarAbouZor/homebrew-tui-journal/tui-journal
```
=> Fixed: Fix Homebrew GitHub Action

.github/workflows/main.yml, Cargo.toml
This PR closes #497 
It includes:
* Run the CI checks on both latest and the minimal supported rust version
* Increase Rust minimal Version to 1.81.0
* Fix undefined rust version in previous runs.
* Add verbose flag for `rust clippy`
=> CI: Include minimal supported rust version & Increase Min Version

Cargo.lock, Cargo.toml, README.md, src/app/filter/criterion.rs, src/app/test/filter.rs, src/app/ui/fuzz_find/mod.rs, src/main.rs
This PR closes #490 
It provides smart-case for Fuzzy finder and filter by default
* For fuzzy finder I just enabled the option on `SkimMatcherV2`
* For filter I add basic implementation for title since they are to long, but for content I've used [the crate aho_corasick](https://docs.rs/aho-corasick/latest/aho_corasick/)
* Unit tests for filter are added as well.
=> Added: Smart Case for Filter & Fuzzy Finder

Cargo.lock, Cargo.toml
This PR:
* Simplified the versions in `Cargo.toml` to make them get updated with `cargo update`
* Run `cargo update`
=> Changed: Update dependencies & Simplified versions

README.md
A new [FreeBSD port](https://www.freshports.org/textproc/tui-journal) was published for tui-journal.
Fixes #506
=> Add FreeBSD install instructions to README

README.md, src/app/mod.rs, src/app/state.rs, src/app/ui/entries_list/mod.rs, src/app/ui/export_popup/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/fuzz_find/mod.rs, src/cli/mod.rs, src/main.rs, src/settings/mod.rs
This PR closes #504 
It provides the following:
* Change the default state directory on Linux and FreeBSD from `data` to `state` directories + Implement Moving the current states from the old directory to the new one.
* CLI argument to set the path for the configuration file.
* Add configuration to change the path of the state directory.
* Clippy Fixes
=> Added: Config path via CLI & State Path configurable & Fix default state path

README.md, src/app/ui/commands/entries_list_cmd.rs, src/settings/external_editor.rs
This PR closes #510 
It provides an option to set the extension of the temp file used with the external editor. 
This influences syntax highlighting in external editor (e.g., `md` for Markdown support).
=> Config for extension of temp file in external editor

Cargo.lock, Cargo.toml, README.md, THEMES.md, src/app/mod.rs, src/app/runner.rs, src/app/ui/editor/mod.rs, src/app/ui/entries_list/mod.rs, src/app/ui/entry_popup/mod.rs, src/app/ui/entry_popup/tags.rs, src/app/ui/export_popup/mod.rs, src/app/ui/filter_popup/mod.rs, src/app/ui/fuzz_find/mod.rs, src/app/ui/mod.rs, src/app/ui/msg_box/mod.rs, src/app/ui/sort_popup/mod.rs, src/app/ui/themes/editor_styles.rs, src/app/ui/themes/general_styles.rs, src/app/ui/themes/journals_list_styles.rs, src/app/ui/themes/mod.rs, src/app/ui/themes/msgbox.rs, src/app/ui/themes/serialization.rs, src/app/ui/themes/style.rs, src/cli/commands.rs, src/cli/mod.rs, src/main.rs
This PR closes #509 
It provides a complete framework to enable users to override the styles and colors of the app.
This PR includes:
* Move all styles into one central struct with default implementation.
* Users can override themes by defining them in `themes.toml` file in `tui-journal` directory within the config directory (More in themes documentations)
* CLI sub-commands to print default themes, print the path of themes files and write the default themes directly to the file.
* New `Themes.md` Document to explain theming in details.
* Small changes on current themes, enabling unified feel on UI across the app
* Cover serializing of theme with a lot of unit tests
* Update README with small fixes
=> Added: Custom themes on user level & Styles improvements

README.md, src/cli/mod.rs
This PR continues #539 
It fixes the typo from the readme in the help output + It fix other typos too
=> Fix: Fix Typos in CLI help & README

Cargo.lock, Cargo.toml, backend/src/json.rs, src/main.rs
This PR updates the dependencies to their latest versions. Also it provides clippy fixes
`crossterm` can't be updated to the latest version because `tui-textarea` isn't compatible with it yet.
=> Update Dependencies & Clippy fixes

Cargo.lock, Cargo.toml, README.md
This PR solves the [comment](https://github.com/AmmarAbouZor/tui-journal/issues/5#issuecomment-3120665392).
It removes the Dependency to `Native-TLS` feature in `SQLx`, removing `OpenSSL` on Linux.
Native TLS isn't needed because SQLite files are saved always locally and not over a network. (Thanks @goto-dev-null for pointing that out!).
The reason for adding it in the first place was most probably because `SQLx` offered it bundled with tokio runtime support which isn't the case anymore.
This PR updates the README accordingly and updates other dependencies
=> Remove Dependencies to OpenSSL & Native TLS
